# Generated by Django 3.2.8 on 2021-10-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='echouser',
            name='role',
            field=models.CharField(default='guest', max_length=10),
        ),
    ]
