# Generated by Django 3.2.8 on 2021-10-13 17:03

from django.db import migrations, models


def add_test_user_records(apps, schema_editor):
    EchoUser = apps.get_model("app", "EchoUser")

    # hash of the password "password"
    password = "pbkdf2_sha256$260000$fk3T3epChDUvtLoxO61XXL$jWqXN7qfaiH4swXbNo+6Vf83XvUqXsbYFLkfUucX6vs="
    EchoUser.objects.create(first_name="Gia", last_name="Robinson", role="editor", email="gia@site.com", password=password)
    EchoUser.objects.create(first_name="Myo", last_name="Khin", role="guest", email="myo@site.com", password=password)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_echouser_role'),
    ]

    operations = [
        migrations.RunPython(
            add_test_user_records, reverse_code=migrations.RunPython.noop
        ),
    ]
