# Generated by Django 3.2.8 on 2021-10-13 17:03

from django.db import migrations


def add_saved_queries(apps, schema_editor):
    SavedQueries = apps.get_model("app", "SavedQueries")

    SavedQueries.objects.create(created="2021-10-15 17:48:26.563297+00", modified="2021-10-15 18:03:16.031821+00", user_id=1, name="Rental titles by customer", content="select\n  c.first_name || ' ' || c.last_name customer_name,\n  c.email customer_email,\n  f.title film_title\nfrom rental r\ninner join customer c\n  on r.customer_id = c.customer_id\ninner join inventory i\n  on r.inventory_id = i.inventory_id\ninner join film f\n  on i.film_id = f.film_id;")
    SavedQueries.objects.create(created="2021-10-15 18:38:52.163382+00", modified="2021-10-15 18:58:25.267832+00", user_id=1, name="Film actors", content="with base as(\n  select\n    a.first_name,\n    a.last_name,\n    count(f.*) film_count\n  from actor a\n  inner join film_actor fa\n    on fa.actor_id = a.actor_id\n  inner join film f\n    on f.film_id = fa.film_id\n  group by a.actor_id\n)\n\nselect *\nfrom base\norder by film_count desc")
    SavedQueries.objects.create(created="2021-10-15 19:05:10.531122+00", modified="2021-10-15 19:05:10.531149+00", user_id=2, name="📽️ film list", content="select * from nicer_but_slower_film_list")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_savedqueries'),
    ]

    operations = [
        migrations.RunPython(
            add_saved_queries, reverse_code=migrations.RunPython.noop
        ),
    ]
