version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ../.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./mock_data.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/var/lib/postgresql/data/
    ports:
      - 5555:5432
    environment:
      - POSTGRES_DB=echo
      - POSTGRES_USER=echo_user
      - POSTGRES_PASSWORD=echo_password
