version: '3.8'

services:
  backend:
    build: .
    command: python ./echo/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ../.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - sql_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=echo
      - POSTGRES_USER=echo_user
      - POSTGRES_PASSWORD=echo_password

volumes:
  sql_data:
  